const express = require("express");
let bodyParser = require("body-parser");
const app = express();
const cors = require("cors");
const router = express.Router();
const expressValidator = require('express-validator');
const multer = require('multer')
router.use(expressValidator())
app.use(cors({origin: "*"}));
app.use(bodyParser.json());
const fs = require('fs')
app.use(bodyParser.urlencoded({ extended: true }))
//port
const hostname = '0.0.0.0';
const port = process.env.PORT || 3000;
app.listen(port, hostname, () => {
    console.log("bien connecté");
    console.log(`Server running at https://${hostname}:${port}`);
});

app.get("/", (req, res) => {
    res.send(
        "<h1 style='text-align: center'>Bienvenue sur SnapTechie Express Js API<br><br>👋</h1>"
    );
});
const snapStorage = multer.diskStorage({
    destination: (req, image, callBack) => {
        callBack(null, 'assets')
    },
    filename: (req, image, callBack) => {
        callBack(null, image.name.filename)
    }
})

let snapUpload = multer({storage: snapStorage, dest: '../assets'})

app.post('/snap',(req, res) => {
    fs.writeFile('./out.png', req.body.imgsource, 'base64', (err) => {
        if (err) throw err
    })
    res.status(200)
})


const upload = multer({dest: 'uploads/'}); //setting the default folder for multer

app.post('/snap',upload.single('fileData'), (req, res,next) => {
    console.log(req.file);//this will be automatically set by multer
    console.log(req.body);
    //below code will read the data from the upload folder. Multer     will automatically upload the file in that folder with an  autogenerated name
    fs.readFile(req.file.path,(err, contents)=> {
        if (err) {
            console.log('Error: ', err);
        }else{
            console.log('File contents ',contents);
        }
    });
});


app.use(bodyParser.urlencoded({ extended: true }))

app.post('/upload/snap', (req, res) => {
    fs.writeFile('./out.png', req.body.imgsource, 'base64', (err) => {
        if (err) throw err
    })
    res.status(200)
})
